# Generated by Django 4.1.9 on 2023-12-08 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Lumber', 'Lumber/Lumber Products'), ('Wildlife', 'Wildlife/Animals')], max_length=100)),
                ('importer_name', models.CharField(max_length=100)),
                ('importer_address', models.CharField(max_length=100)),
                ('importer_city', models.CharField(max_length=100)),
                ('importer_state', models.CharField(max_length=100)),
                ('importer_zip', models.CharField(max_length=100)),
                ('importer_country', models.CharField(max_length=100)),
                ('importer_phone', models.CharField(max_length=100)),
                ('importer_email', models.CharField(max_length=100)),
                ('importer_social', models.CharField(max_length=100)),
                ('importer_business_number', models.CharField(max_length=100)),
                ('exporter_name', models.CharField(max_length=100)),
                ('exporter_address', models.CharField(max_length=100)),
                ('exporter_city', models.CharField(max_length=100)),
                ('exporter_state', models.CharField(max_length=100)),
                ('exporter_zip', models.CharField(max_length=100)),
                ('exporter_country', models.CharField(max_length=100)),
                ('mode_of_transport', models.CharField(choices=[('Air', 'Air'), ('Sea', 'Sea'), ('Land', 'Land')], max_length=100)),
                ('port_of_entry', models.CharField(max_length=100)),
                ('port_of_exit', models.CharField(max_length=100)),
                ('treatment', models.CharField(choices=[('Pressure', 'Pressure'), ('Kiln', 'Kiln'), ('Chemical', 'Chemical'), ('Air Dry', 'Air Dry'), ('None', 'None')], max_length=100)),
                ('date_received', models.DateField()),
                ('date_approved', models.DateField()),
                ('date_expires', models.DateField()),
                ('packaging_list_approved', models.BooleanField()),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Conditional', 'Approved with Conditions'), ('Not Approved', 'Not Approved')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('grade', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.application')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.goods')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='description_of_goods',
            field=models.ManyToManyField(through='licensing.Species', to='licensing.goods'),
        ),
    ]
