# Generated by Django 4.1.9 on 2023-12-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Conditional', 'Approved with Conditions'), ('Not Approved', 'Not Approved')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
