# Generated by Django 4.1.9 on 2024-03-15 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description_of_goods',
            field=models.ManyToManyField(blank=True, null=True, through='licensing.Species', to='licensing.goods'),
        ),
        migrations.AlterField(
            model_name='species',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licensing.application'),
        ),
    ]
