# Generated by Django 4.1.9 on 2024-03-15 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licensing', '0005_alter_application_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='packaging_list_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
