# Generated by Django 4.1.9 on 2024-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0010_lumber_speciestype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lumber',
            name='application',
        ),
        migrations.RemoveField(
            model_name='species',
            name='Application',
        ),
        migrations.AddField(
            model_name='application',
            name='lumber_details',
            field=models.ManyToManyField(blank=True, to='licensing.lumber'),
        ),
        migrations.AddField(
            model_name='application',
            name='species_details',
            field=models.ManyToManyField(blank=True, to='licensing.species'),
        ),
    ]
