# Generated by Django 4.1.9 on 2024-04-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0012_application_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumber',
            name='local_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
