# Generated by Django 4.1.9 on 2024-04-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0013_alter_lumber_local_name_alter_lumber_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumber',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
