# Generated by Django 4.1.9 on 2024-04-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0014_alter_lumber_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumber',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
