# Generated by Django 4.1.9 on 2024-04-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0015_alter_lumber_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='goods',
            field=models.CharField(choices=[('Lumber', 'Lumber/Lumber Products'), ('Wildlife', 'Wildlife/Animals'), ('Plants', 'Plants/Plant Products'), ('Other', 'Other')], default='Lumber', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='approval',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Conditional', 'Approved with Conditions'), ('Not Approved', 'Not Approved'), ('In Review', 'In Review')], default='In Review', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], max_length=100),
        ),
    ]
