# Generated by Django 4.1.9 on 2024-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0017_application_importer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_registry_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='treatment',
            field=models.CharField(choices=[('Pressure', 'Pressure'), ('Kiln', 'Kiln'), ('Chemical', 'Chemical'), ('Air Dry', 'Air Dry'), ('None', 'None'), ('Other', 'Other')], max_length=100),
        ),
    ]
