# Generated by Django 4.1.9 on 2024-05-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0019_application_permit_number_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
