# Generated by Django 4.1.9 on 2024-06-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0020_profile_business_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='importer_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='other_treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='port_of_entry',
            field=models.CharField(blank=True, choices=[('Western Border', 'Western Border'), ('Port of Belize', 'Port of Belize, Belize City'), ('Northern Border', 'Northern Border'), ('PGIA', 'Philip Goldson International Airport'), ('Big Creek', 'Big Creek Port, Stann Creek')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='port_of_exit',
            field=models.CharField(blank=True, choices=[('Western Border', 'Western Border'), ('Port of Belize', 'Port of Belize, Belize City'), ('Northern Border', 'Northern Border'), ('PGIA', 'Philip Goldson International Airport'), ('Big Creek', 'Big Creek Port, Stann Creek')], max_length=100, null=True),
        ),
    ]
