# Generated by Django 4.1.9 on 2024-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0021_application_importer_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source_of_lumber',
            field=models.CharField(blank=True, choices=[('License', 'Forest License'), ('Sawmill', 'Sawmill/Lumber Yard')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lumber',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
