# Generated by Django 4.1.9 on 2024-06-07 04:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0026_application_cites_permit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumber',
            name='cubic_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='importer_business_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
        migrations.AlterField(
            model_name='application',
            name='importer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='US'),
        ),
    ]
