# Generated by Django 4.1.9 on 2024-06-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0028_rename_name_species_local_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeciesType',
        ),
    ]
