# Generated by Django 4.1.9 on 2024-06-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0030_citeslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='citeslist',
            name='common_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
