# Generated by Django 4.1.9 on 2024-06-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0032_rename_port_of_entry_application_port_of_entry_bz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceOfLumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_lumber', models.CharField(blank=True, choices=[('License', 'Forest License'), ('Sawmill', 'Sawmill/Lumber Yard')], max_length=100, null=True)),
                ('licensee_name', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('validity_period', models.CharField(blank=True, max_length=100, null=True)),
                ('sawmill_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sawmill_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='licensee_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sawmill_address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sawmill_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='validity_period',
        ),
        migrations.RemoveField(
            model_name='application',
            name='source_of_lumber',
        ),
        migrations.AddField(
            model_name='application',
            name='source_of_lumber',
            field=models.ManyToManyField(blank=True, to='licensing.sourceoflumber'),
        ),
    ]
