# Generated by Django 4.1.9 on 2024-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0033_sourceoflumber_remove_application_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='packing_list',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='application',
            name='performa_invoice',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='application',
            name='picture_of_material',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='application',
            name='sawmill_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='application',
            name='zero_balance_receipt',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
