# Generated by Django 4.1.9 on 2024-07-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0034_application_packing_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='CITES_status',
            field=models.CharField(blank=True, choices=[('Appendix I', 'Appendix I'), ('Appendix II', 'Appendix II'), ('Appendix III', 'Appendix III'), ('Not Listed', 'Not Listed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='class_of_goods',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Pet', 'Pet'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='identification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='local_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='number_of_individuals',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
