# Generated by Django 4.1.9 on 2024-07-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0035_alter_species_cites_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='forest_license',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='exporter_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='exporter_zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='importer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='importer_zip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
