# Generated by Django 4.1.9 on 2024-07-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0036_application_forest_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='class_of_goods',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Pet', 'Pet'), ('Flora', 'Flora'), ('Meat', 'Meat'), ('Throphies', 'Hunting Throphies'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
