# Generated by Django 4.1.9 on 2024-07-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0037_alter_species_class_of_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='export_form',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
