# Generated by Django 4.1.9 on 2024-07-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0039_application_certificate_of_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='class_of_goods',
        ),
        migrations.AddField(
            model_name='application',
            name='class_of_goods',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Pet', 'Pet'), ('Flora', 'Flora'), ('Meat', 'Meat'), ('Throphies', 'Hunting Throphies'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
