# Generated by Django 4.1.9 on 2024-09-19 19:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0040_remove_species_class_of_goods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exporter_business_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
        migrations.AddField(
            model_name='application',
            name='exporter_company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exporter_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exporter_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='exporter_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='class_of_goods',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Pet', 'Pet'), ('Flora', 'Flora'), ('Meat', 'Meat'), ('Throphies', 'Hunting Throphies')], max_length=100, null=True),
        ),
    ]
