# Generated by Django 4.1.9 on 2024-09-19 19:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0041_application_exporter_business_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='exporter_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='US'),
        ),
        migrations.AddField(
            model_name='application',
            name='exporter_registry_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
