# Generated by Django 4.1.9 on 2024-09-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0042_application_exporter_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='business_registry_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
