# Generated by Django 4.1.9 on 2024-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0043_application_business_registry_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='species_details',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
