# Generated by Django 4.1.9 on 2024-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0044_species_species_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='species_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='species_details',
        ),
        migrations.AddField(
            model_name='application',
            name='species_details',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
