# Generated by Django 4.1.9 on 2024-09-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0045_remove_species_species_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason_for_import_export',
            field=models.CharField(blank=True, choices=[('Research', 'Research'), ('Companion Species', 'Companion Species'), ('Meat', 'Meat'), ('Trophies', 'Trophy hunting')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='class_of_goods',
            field=models.CharField(blank=True, choices=[('Butterflies', 'Butterflies'), ('Beetles', 'Beetles'), ('Tissue Samples', 'Tissue Samples'), ('Seeds and Bulbs', 'Seeds and Bulbs'), ('Orchid', 'Orchid'), ('Cacti', 'Cacti'), ('Fauna', 'Fauna'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
